keywords_list = [
  {'first': 'add', 'second': 'new', 'third': 'requirement', 'type': 'RQM'},
  {'first': 'add', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'analys', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'backend', 'second': 'frontend', 'third': 'requirement', 'type': 'RQM'},
  {'first': 'change', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'check', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'claim', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'clarificat', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'collect', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'common', 'second': 'features', 'third': '', 'type': 'RQM'},
  {'first': 'complete', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'confirm', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'create', 'second': 'user', 'third': 'manual', 'type': 'DOC'},
  {'first': 'defin', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'deliver', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'describe', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'function', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'general', 'second': 'application', 'third': 'requirement', 'type': 'RQM'},
  {'first': 'identify', 'second': 'business', 'third': 'process', 'type': 'RQM'},
  {'first': 'new', 'second': 'feature', 'third': '', 'type': 'RQM'},
  {'first': 'new', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'provide', 'second': 'business', 'third': 'requirement', 'type': 'RQM'},
  {'first': 'query', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'requirement', 'second': 'change', 'third': '', 'type': 'RQM'},
  {'first': 'requirement', 'second': 'documentation', 'third': '', 'type': 'RQM'},
  {'first': 'requirement', 'second': 'user', 'third': 'stor', 'type': 'RQM'},
  {'first': 'review', 'second': 'use', 'third': 'case', 'type': 'RQM'},
  {'first': 'specify', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'upgrad', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'use', 'second': 'case', 'third': 'confirm', 'type': 'RQM'},
  {'first': 'view', 'second': 'action', 'third': 'requirement', 'type': 'RQM'},
  {'first': 'web', 'second': 'requirement', 'third': '', 'type': 'RQM'},
  {'first': 'education', 'second': '', 'third': '', 'type': 'EDU'},
  {'first': 'training', 'second': '', 'third': '', 'type': 'EDU'},
  {'first': 'acceptance', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'account', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'application', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'auto', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'automate', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'automatic', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'backup', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'broker', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'change', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'common', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'conduct', 'second': 'smoke', 'third': 'test', 'type': 'TST'},
  {'first': 'controller', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'crash', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'creat', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'creat', 'second': 'frontend', 'third': 'test', 'type': 'TST'},
  {'first': 'creat', 'second': 'test', 'third': 'data', 'type': 'TST'},
  {'first': 'creat', 'second': 'test', 'third': 'scenario', 'type': 'TST'},
  {'first': 'customer', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'deliver', 'second': 'test', 'third': 'data', 'type': 'TST'},
  {'first': 'enable', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'end', 'second': 'to', 'third': 'test', 'type': 'TST'},
  {'first': 'end2end', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'execute', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'exploration', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'file', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'fix', 'second': 'test', 'third': 'case', 'type': 'TST'},
  {'first': 'fix', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'form', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'front', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'frontend', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'general', 'second': 'ledger', 'third': 'test', 'type': 'TST'},
  {'first': 'general', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'generator', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'gui', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'handle', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'initial', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'integration', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'internal', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'load', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'maintenance', 'second': 'auto', 'third': 'test', 'type': 'TST'},
  {'first': 'module', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'need', 'second': 'more', 'third': 'tests', 'type': 'TST'},
  {'first': 'new', 'second': 'test', 'third': 'case', 'type': 'TST'},
  {'first': 'owasp', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'performance', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'pre', 'second': 'prod', 'third': 'test', 'type': 'TST'},
  {'first': 'prepar', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'prepar', 'second': 'new', 'third': 'test', 'type': 'TST'},
  {'first': 'prepar', 'second': 'unit', 'third': 'test', 'type': 'TST'},
  {'first': 'print', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'product', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'QA', 'second': '', 'third': '', 'type': 'TST'},
  {'first': 'regress', 'second': 'qa', 'third': '', 'type': 'TST'},
  {'first': 'regression', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'release', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'reminder', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'renewal', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'robot', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'script', 'second': 'run', 'third': 'test', 'type': 'TST'},
  {'first': 'script', 'second': 'test', 'third': 'user', 'type': 'TST'},
  {'first': 'script', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'smoke', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'sql', 'second': 'testsuite', 'third': '', 'type': 'TST'},
  {'first': 'support', 'second': 'testing', 'third': '', 'type': 'TST'},
  {'first': 'technical', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'affinition', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'case', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'conduct', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'document', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'expansion', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'gl', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'implementation', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'launch', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'microservice', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'plan', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'preparation', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'problems', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'report', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'result', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'scenario', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'support', 'third': '', 'type': 'TST'},
  {'first': 'test', 'second': 'verification', 'third': '', 'type': 'TST'},
  {'first': 'uat', 'second': 'test', 'third': 'scenario', 'type': 'TST'},
  {'first': 'uat', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'unit', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'update', 'second': 'test', 'third': 'data', 'type': 'TST'},
  {'first': 'user', 'second': 'acceptance', 'third': 'test', 'type': 'TST'},
  {'first': 'web', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'withdraw', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'workflow', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'writ', 'second': 'test', 'third': '', 'type': 'TST'},
  {'first': 'writ', 'second': 'unit', 'third': 'test', 'type': 'TST'},
  {'first': 'migrat', 'second': 'account', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'after', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'agent', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'analyze', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'case', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'check', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'claim', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'comission', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'contract', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'customer', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'data', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'departm', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'document', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'employee', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'error', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'file', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'glas', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'item', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'ol', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'parallel', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'partner', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'party', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'perform', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'person', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'polic', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'prep', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'prepar', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'process', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'product', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'raminder', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'sale', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'scheduler', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'script', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'servic', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'split', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'summar', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'system', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'table', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'task', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'test', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'wgv', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'wrongly', 'third': '', 'type': 'MIGR'},
  {'first': 'migrat', 'second': 'unfal', 'third': '', 'type': 'MIGR'},
  {'first': 'release', 'second': 'management', 'third': '', 'type': 'BLD'},
  {'first': 'install', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'prepar', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'production', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'don''t', 'second': 'compile', 'third': '', 'type': 'BLD'},
  {'first': 'management', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'deploy', 'second': 'application', 'third': '', 'type': 'BLD'},
  {'first': 'deploy', 'second': 'backend', 'third': '', 'type': 'BLD'},
  {'first': 'procedure', 'second': 'deploy', 'third': '', 'type': 'BLD'},
  {'first': 'script', 'second': 'deploy', 'third': '', 'type': 'BLD'},
  {'first': 'jenkins', 'second': 'job', 'third': 'deploy', 'type': 'BLD'},
  {'first': 'auto', 'second': 'deploy', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'problem', 'third': '', 'type': 'BLD'},
  {'first': 'release', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'install', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'run', 'second': 'build-ci', 'third': '', 'type': 'BLD'},
  {'first': 'jenkins', 'second': 'job', 'third': 'deploy', 'type': 'BLD'},
  {'first': 'install', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'prepare', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'run', 'third': 'project', 'type': 'BLD'},
  {'first': 'build', 'second': 'frontend', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'backend', 'third': '', 'type': 'BLD'},
  {'first': 'jenkins', 'second': 'job', 'third': 'deploy', 'type': 'BLD'},
  {'first': 'product', 'second': 'version', 'third': 'build', 'type': 'BLD'},
  {'first': 'continous', 'second': 'integration', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'data', 'third': 'base', 'type': 'BLD'},
  {'first': 'dry', 'second': 'run', 'third': 'build', 'type': 'BLD'},
  {'first': 'classpath', 'second': 'compiler', 'third': '', 'type': 'BLD'},
  {'first': 'way', 'second': 'deployment', 'third': '', 'type': 'BLD'},
  {'first': 'check', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'create', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'add', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'deploy', 'second': 'war', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'install', 'third': 'job', 'type': 'BLD'},
  {'first': 'remove', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'docker', 'second': 'deploy', 'third': '', 'type': 'BLD'},
  {'first': 'script', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'build', 'second': 'error', 'third': '', 'type': 'BLD'},
  {'first': 'error', 'second': 'building', 'third': '', 'type': 'BLD'},
  {'first': 'incremental', 'second': 'deployment', 'third': '', 'type': 'BLD'},
  {'first': 'npm', 'second': 'build', 'third': '', 'type': 'BLD'},
  {'first': 'script', 'second': 'control', 'third': 'CI', 'type': 'BLD'},
  {'first': 'account', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'accounting', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'add', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'adf', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'adjust', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'agent', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'algorithm', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'automatic', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'batch', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'batch', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'case', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'change', 'second': 'client', 'third': 'config', 'type': 'CFG'},
  {'first': 'change', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'change', 'second': 'configuration', 'third': '', 'type': 'CFG'},
  {'first': 'change', 'second': 'preference', 'third': '', 'type': 'CFG'},
  {'first': 'check', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'check', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'claim', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'claim', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'commision', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'component', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'correct', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'create', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'create', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'create', 'second': 'system', 'third': 'preferences', 'type': 'CFG'},
  {'first': 'currency', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'customer', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'default', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'default', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'dictionary', 'second': 'definition', 'third': '', 'type': 'CFG'},
  {'first': 'file', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'initial', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'insurer', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'language', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'letter', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'missing', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'new', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'parameter', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'party', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'payment', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'policy', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'prepar', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'print', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'print', 'second': 'definition', 'third': '', 'type': 'CFG'},
  {'first': 'printer', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'product', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'profile', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'proper', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'relation', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'reminder', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'remove', 'second': 'attribute', 'third': '', 'type': 'CFG'},
  {'first': 'review', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'role', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'setup', 'second': 'configuration', 'third': '', 'type': 'CFG'},
  {'first': 'setup', 'second': 'environment', 'third': '', 'type': 'CFG'},
  {'first': 'setup', 'second': 'print', 'third': '', 'type': 'CFG'},
  {'first': 'should', 'second': 'be', 'third': 'config', 'type': 'CFG'},
  {'first': 'site', 'second': 'preference', 'third': '', 'type': 'CFG'},
  {'first': 'system', 'second': 'preference', 'third': '', 'type': 'CFG'},
  {'first': 'tariff', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'treatment', 'second': 'setting', 'third': '', 'type': 'CFG'},
  {'first': 'update', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'update', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'update', 'second': 'price', 'third': 'settings', 'type': 'CFG'},
  {'first': 'user', 'second': 'config', 'third': '', 'type': 'CFG'},
  {'first': 'user', 'second': 'setup', 'third': '', 'type': 'CFG'},
  {'first': 'validation', 'second': 'definition', 'third': '', 'type': 'CFG'},
  {'first': 'wrong', 'second': 'settings', 'third': '', 'type': 'CFG'},
  {'first': 'daily', 'second': 'work', 'third': 'planning', 'type': 'PM'},
  {'first': 'jira', 'second': 'review', 'third': 'management', 'type': 'PM'},
  {'first': 'jira', 'second': 'review', 'third': '', 'type': 'PM'},
  {'first': 'jira', 'second': 'status', 'third': 'review', 'type': 'PM'},
  {'first': 'prepar', 'second': 'workshop', 'third': '', 'type': 'RQM'},
  {'first': 'algorithm', 'second': 'review', 'third': '', 'type': 'RVW'},
  {'first': 'develop', 'second': 'review', 'third': '', 'type': 'RVW'},
  {'first': 'documentation', 'second': 'review', 'third': '', 'type': 'RVW'},
  {'first': 'requirement', 'second': 'review', 'third': '', 'type': 'RVW'},
  {'first': 'review', 'second': 'implementation', 'third': '', 'type': 'RVW'},
  {'first': 'script', 'second': 'review', 'third': '', 'type': 'RVW'},
  {'first': 'regression', 'second': 'result', 'third': 'review', 'type': 'TST'},
  {'first': 'result', 'second': 'review', 'third': '', 'type': 'TST'},
  {'first': 'access', 'second': 'application', 'third': 'wildfly', 'type': 'ADM'},
  {'first': 'access', 'second': 'customer', 'third': '', 'type': 'ADM'},
  {'first': 'access', 'second': 'database', 'third': '', 'type': 'ADM'},
  {'first': 'access', 'second': 'project', 'third': '', 'type': 'ADM'},
  {'first': 'access', 'second': 'samba', 'third': '', 'type': 'ADM'},
  {'first': 'access', 'second': 'vpn', 'third': '', 'type': 'ADM'},
  {'first': 'add', 'second': 'branch', 'third': '', 'type': 'ADM'},
  {'first': 'add', 'second': 'hostname', 'third': 'dns', 'type': 'ADM'},
  {'first': 'add', 'second': 'into', 'third': 'firewall', 'type': 'ADM'},
  {'first': 'add', 'second': 'plugin', 'third': 'installation', 'type': 'ADM'},
  {'first': 'add ', 'second': 'instance', 'third': '', 'type': 'ADM'},
  {'first': 'add ', 'second': 'pipeline', 'third': '', 'type': 'ADM'},
  {'first': 'address', 'second': 'access', 'third': 'environment', 'type': 'ADM'},
  {'first': 'adjust', 'second': 'job ', 'third': 'handle', 'type': 'ADM'},
  {'first': 'asp', 'second': 'solution', 'third': 'server', 'type': 'ADM'},
  {'first': 'automatic', 'second': 'release', 'third': '', 'type': 'ADM'},
  {'first': 'backup', 'second': 'database', 'third': '', 'type': 'ADM'},
  {'first': 'buy', 'second': 'ssl', 'third': 'wildcard', 'type': 'ADM'},
  {'first': 'certification', 'second': 'web ', 'third': 'service', 'type': 'ADM'},
  {'first': 'change', 'second': 'database', 'third': 'script', 'type': 'ADM'},
  {'first': 'check', 'second': 'disk', 'third': 'server', 'type': 'ADM'},
  {'first': 'clean', 'second': 'git', 'third': 'repository', 'type': 'ADM'},
  {'first': 'clean', 'second': 'repo', 'third': '', 'type': 'ADM'},
  {'first': 'clean', 'second': 'tsfa', 'third': 'restore', 'type': 'ADM'},
  {'first': 'configure', 'second': 'customer', 'third': 'project', 'type': 'ADM'},
  {'first': 'configure', 'second': 'customer', 'third': 'project', 'type': 'ADM'},
  {'first': 'configure', 'second': 'customer', 'third': '', 'type': 'ADM'},
  {'first': 'copy', 'second': 'jenkins', 'third': 'job', 'type': 'ADM'},
  {'first': 'crash', 'second': 'report', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'jenkins', 'third': 'job', 'type': 'ADM'},
  {'first': 'create', 'second': 'jira', 'third': 'project', 'type': 'ADM'},
  {'first': 'create', 'second': 'network ', 'third': 'share', 'type': 'ADM'},
  {'first': 'create', 'second': 'permanent', 'third': 'redirect', 'type': 'ADM'},
  {'first': 'create', 'second': 'pipeline', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'project', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'script', 'third': 'installation', 'type': 'ADM'},
  {'first': 'create', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'create', 'second': 'svn', 'third': 'project', 'type': 'ADM'},
  {'first': 'create ', 'second': 'account', 'third': '', 'type': 'ADM'},
  {'first': 'credentials', 'second': 'jenkins', 'third': 'store', 'type': 'ADM'},
  {'first': 'custom', 'second': 'field', 'third': '', 'type': 'ADM'},
  {'first': 'dedicated', 'second': 'server', 'third': 'performance', 'type': 'ADM'},
  {'first': 'delete', 'second': 'account', 'third': '', 'type': 'ADM'},
  {'first': 'deploy', 'second': 'production', 'third': '', 'type': 'ADM'},
  {'first': 'deploy ', 'second': 'error', 'third': '', 'type': 'ADM'},
  {'first': 'deployment', 'second': 'process', 'third': '', 'type': 'ADM'},
  {'first': 'disaster', 'second': 'recovery', 'third': 'postgres', 'type': 'ADM'},
  {'first': 'disaster', 'second': 'recovery', 'third': '', 'type': 'ADM'},
  {'first': 'dns', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'docker', 'second': 'update', 'third': '', 'type': 'ADM'},
  {'first': 'download ', 'second': 'backup', 'third': 'database', 'type': 'ADM'},
  {'first': 'empty', 'second': 'tsfa', 'third': 'folder', 'type': 'ADM'},
  {'first': 'environment', 'second': 'jenkins', 'third': 'build', 'type': 'ADM'},
  {'first': 'environment', 'second': 'prepar', 'third': '', 'type': 'ADM'},
  {'first': 'environment', 'second': 'setup', 'third': '', 'type': 'ADM'},
  {'first': 'error', 'second': 'environment', 'third': 'building', 'type': 'ADM'},
  {'first': 'external', 'second': 'access', 'third': 'environment', 'type': 'ADM'},
  {'first': 'fix', 'second': 'script', 'third': 'management', 'type': 'ADM'},
  {'first': 'full', 'second': 'tablespace', 'third': '', 'type': 'ADM'},
  {'first': 'gcloud', 'second': 'jenkins', 'third': 'job', 'type': 'ADM'},
  {'first': 'grant', 'second': 'access', 'third': 'resource', 'type': 'ADM'},
  {'first': 'grant ', 'second': 'access', 'third': 'database', 'type': 'ADM'},
  {'first': 'high', 'second': 'cpu', 'third': 'usage', 'type': 'ADM'},
  {'first': 'implement', 'second': 'security ', 'third': 'check', 'type': 'ADM'},
  {'first': 'import', 'second': 'trace', 'third': 'tables', 'type': 'ADM'},
  {'first': 'increase', 'second': 'disk', 'third': '', 'type': 'ADM'},
  {'first': 'increase', 'second': 'space', 'third': 'disk', 'type': 'ADM'},
  {'first': 'infrastructure', 'second': 'delivery', 'third': '', 'type': 'ADM'},
  {'first': 'infrastructure', 'second': 'support', 'third': '', 'type': 'ADM'},
  {'first': 'install', 'second': 'application', 'third': 'server', 'type': 'ADM'},
  {'first': 'install', 'second': 'complete', 'third': 'release', 'type': 'ADM'},
  {'first': 'install', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'install', 'second': 'local ', 'third': 'server', 'type': 'ADM'},
  {'first': 'install', 'second': 'oracle', 'third': '', 'type': 'ADM'},
  {'first': 'install', 'second': 'web', 'third': 'application', 'type': 'ADM'},
  {'first': 'integration', 'second': 'with', 'third': 'ldap', 'type': 'ADM'},
  {'first': 'java', 'second': 'version', 'third': 'change', 'type': 'ADM'},
  {'first': 'jenkins', 'second': 'job', 'third': 'environment', 'type': 'ADM'},
  {'first': 'jenkins', 'second': 'job', 'third': '', 'type': 'ADM'},
  {'first': 'jenkins', 'second': 'pipeline', 'third': '', 'type': 'ADM'},
  {'first': 'jenkins', 'second': 'slave', 'third': '', 'type': 'ADM'},
  {'first': 'jira', 'second': 'webapp', 'third': 'server', 'type': 'ADM'},
  {'first': 'jmeter', 'second': 'pipeline', 'third': '', 'type': 'ADM'},
  {'first': 'job', 'second': 'copy', 'third': 'cloud', 'type': 'ADM'},
  {'first': 'job', 'second': 'environmet', 'third': '', 'type': 'ADM'},
  {'first': 'job ', 'second': 'deploy', 'third': 'jenkins', 'type': 'ADM'},
  {'first': 'listener', 'second': 'is', 'third': 'down', 'type': 'ADM'},
  {'first': 'local', 'second': 'printer', 'third': 'configuration', 'type': 'ADM'},
  {'first': 'log', 'second': 'docker', 'third': 'compose', 'type': 'ADM'},
  {'first': 'mail', 'second': 'configuration', 'third': '', 'type': 'ADM'},
  {'first': 'managing', 'second': 'release', 'third': '', 'type': 'ADM'},
  {'first': 'migrate ', 'second': 'dockers', 'third': '', 'type': 'ADM'},
  {'first': 'monitoring', 'second': 'development', 'third': 'server', 'type': 'ADM'},
  {'first': 'new', 'second': 'field', 'third': 'jira', 'type': 'ADM'},
  {'first': 'new', 'second': 'jira', 'third': 'account', 'type': 'ADM'},
  {'first': 'new', 'second': 'tablespace', 'third': '', 'type': 'ADM'},
  {'first': 'no', 'second': 'space', 'third': 'device', 'type': 'ADM'},
  {'first': 'performance', 'second': 'problems', 'third': '', 'type': 'ADM'},
  {'first': 'please', 'second': 'fix', 'third': 'weblogic', 'type': 'ADM'},
  {'first': 'please', 'second': 'upload', 'third': 'environment', 'type': 'ADM'},
  {'first': 'prepar', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'print', 'second': 'server', 'third': 'configuration', 'type': 'ADM'},
  {'first': 'print', 'second': 'setup', 'third': '', 'type': 'ADM'},
  {'first': 'problem', 'second': 'repository', 'third': '', 'type': 'ADM'},
  {'first': 'problem', 'second': 'weblogic', 'third': 'domain', 'type': 'ADM'},
  {'first': 'procedure', 'second': 'incremental', 'third': 'deployment', 'type': 'ADM'},
  {'first': 'procedure', 'second': 'refresh', 'third': 'environment', 'type': 'ADM'},
  {'first': 'production', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'production', 'second': 'upgrade', 'third': 'docker', 'type': 'ADM'},
  {'first': 'provide', 'second': 'access', 'third': '', 'type': 'ADM'},
  {'first': 'raising', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'remove', 'second': 'components', 'third': '', 'type': 'ADM'},
  {'first': 'repair', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'repository', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'reset', 'second': 'password', 'third': '', 'type': 'ADM'},
  {'first': 'restart', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'result', 'second': 'test', 'third': 'jenkins', 'type': 'ADM'},
  {'first': 'routing', 'second': 'host', 'third': '', 'type': 'ADM'},
  {'first': 'security', 'second': 'service', 'third': 'review', 'type': 'ADM'},
  {'first': 'security', 'second': 'setup', 'third': '', 'type': 'ADM'},
  {'first': 'server', 'second': 'configure', 'third': '', 'type': 'ADM'},
  {'first': 'server', 'second': 'web', 'third': 'application', 'type': 'ADM'},
  {'first': 'service', 'second': 'inside ', 'third': 'container', 'type': 'ADM'},
  {'first': 'set up', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'setup', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'setup', 'second': 'server', 'third': '', 'type': 'ADM'},
  {'first': 'sonarqube', 'second': '', 'third': '', 'type': 'ADM'},
  {'first': 'specify', 'second': 'service', 'third': '', 'type': 'ADM'},
  {'first': 'sql', 'second': 'script', 'third': '', 'type': 'ADM'},
  {'first': 'ssl', 'second': 'certificate', 'third': '', 'type': 'ADM'},
  {'first': 'svn', 'second': 'access', 'third': 'for', 'type': 'ADM'},
  {'first': 'svn', 'second': 'return', 'third': 'error', 'type': 'ADM'},
  {'first': 'system', 'second': 'registration', 'third': 'server', 'type': 'ADM'},
  {'first': 'take ', 'second': 'long ', 'third': 'execute', 'type': 'ADM'},
  {'first': 'task', 'second': 'flow', 'third': 'permission', 'type': 'ADM'},
  {'first': 'tomcat', 'second': 'configuration', 'third': '', 'type': 'ADM'},
  {'first': 'tomcat', 'second': 'restart', 'third': '', 'type': 'ADM'},
  {'first': 'too', 'second': 'many ', 'third': 'logs', 'type': 'ADM'},
  {'first': 'update', 'second': 'environment', 'third': '', 'type': 'ADM'},
  {'first': 'upgrade', 'second': 'database', 'third': '', 'type': 'ADM'},
  {'first': 'upgrade', 'second': 'debian', 'third': '', 'type': 'ADM'},
  {'first': 'upgrade', 'second': 'docker', 'third': 'compose', 'type': 'ADM'},
  {'first': 'upgrade', 'second': 'postgresql', 'third': '', 'type': 'ADM'},
  {'first': 'user', 'second': 'credential', 'third': 'binding', 'type': 'ADM'},
  {'first': 'user', 'second': 'group ', 'third': 'jira', 'type': 'ADM'},
  {'first': 'virtual', 'second': 'environment', 'third': 'prepare', 'type': 'ADM'},
  {'first': 'virtual', 'second': 'machine', 'third': 'environment', 'type': 'ADM'},
  {'first': 'vpn', 'second': 'access', 'third': '', 'type': 'ADM'},
  {'first': 'weblogic', 'second': 'access', 'third': '', 'type': 'ADM'},
  {'first': 'wildfly', 'second': 'not ', 'third': 'work', 'type': 'ADM'},
  {'first': 'wildfly ', 'second': 'console', 'third': '', 'type': 'ADM'},
  {'first': 'workflow', 'second': 'maintenance', 'third': '', 'type': 'ADM'},
  {'first': 'workshop', 'second': '', 'third': '', 'type': 'RQM'},
  {'first': 'planning', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'steering', 'second': 'committee', 'third': '', 'type': 'MIT'},
  {'first': 'evening', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'internal', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'follow', 'second': 'up', 'third': 'meeting', 'type': 'MIT'},
  {'first': 'status', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'synchronization', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': '1:1', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'weekly', 'second': 'conference', 'third': '', 'type': 'MIT'},
  {'first': 'stand up', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'internal', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'issue', 'second': 'overview', 'third': 'meeting', 'type': 'MIT'},
  {'first': 'follow up', 'second': 'meeting', 'third': '', 'type': 'MIT'},
  {'first': 'brainstrorm', 'second': 'session', 'third': '', 'type': 'MIT'},
  {'first': 'prepare', 'second': 'agenda', 'third': '', 'type': 'PM'},
  {'first': 'release', 'second': 'introduction', 'third': '', 'type': 'PM'},
  {'first': 'meeting', 'second': 'presentation', 'third': '', 'type': 'PM'},
  {'first': 'documentation', 'second': 'product', 'third': '', 'type': 'PM'},
  {'first': 'onsite', 'second': 'support', 'third': '', 'type': 'PM'},
  {'first': 'weekly', 'second': 'planning', 'third': '', 'type': 'PM'},
  {'first': 'project', 'second': 'estimate', 'third': '', 'type': 'PM'},
  {'first': 'gl', 'second': 'analysis', 'third': '', 'type': 'PM'},
  {'first': 'dictionar', 'second': 'for', 'third': 'product', 'type': 'PM'},
  {'first': 'project', 'second': 'management', 'third': '', 'type': 'PM'},
  {'first': 'review', 'second': 'missing', 'third': 'point', 'type': 'PM'},
  {'first': 'reschedule', 'second': '', 'third': '', 'type': 'PM'},
  {'first': 'estimation', 'second': 'task', 'third': '', 'type': 'PM'},
  {'first': 'presentation', 'second': 'for', 'third': 'meeting', 'type': 'PM'},
  {'first': 'agenda', 'second': 'for', 'third': 'workshop', 'type': 'PM'},
  {'first': 'sprint', 'second': 'planning', 'third': '', 'type': 'PM'},
  {'first': 'prepare', 'second': 'proposal', 'third': '', 'type': 'PM'},
  {'first': 'workshop', 'second': 'support', 'third': 'task', 'type': 'PM'},
  {'first': 'cancelation', 'second': 'contract', 'third': '', 'type': 'PM'},
  {'first': 'review', 'second': 'estimate', 'third': '', 'type': 'PM'},
  {'first': 'project', 'second': 'management', 'third': '', 'type': 'PM'},
  {'first': 'retrospection', 'second': '', 'third': '', 'type': 'PM'},
  {'first': 'jira', 'second': 'administration', 'third': '', 'type': 'PM'},
  {'first': 'project', 'second': 'prepar', 'third': '', 'type': 'PM'},
  {'first': 'budget', 'second': 'report', 'third': '', 'type': 'PM'},
  {'first': 'retro', 'second': 'plan', 'third': '', 'type': 'PM'},
  {'first': 'managament', 'second': 'meeting', 'third': '', 'type': 'PM'},
  {'first': 'plan', 'second': 'work', 'third': '', 'type': 'PM'},
  {'first': 'planning', 'second': 'work', 'third': 'sprint', 'type': 'PM'},
  {'first': 'consultation', 'second': 'customer', 'third': '', 'type': 'CUST'},
  {'first': 'summary', 'second': 'customer', 'third': '', 'type': 'CUST'},
  {'first': 'onsite', 'second': 'support', 'third': '', 'type': 'CUST'},
  {'first': 'issue', 'second': 'support', 'third': '', 'type': 'CUST'},
  {'first': 'first', 'second': 'line', 'third': 'support', 'type': 'CUST'},
  {'first': 'post', 'second': 'production', 'third': 'support', 'type': 'CUST'},
  {'first': 'status', 'second': 'meeting', 'third': 'customer', 'type': 'MIT'},
  {'first': 'production', 'second': 'onsite', 'third': 'support', 'type': 'CUST'},
  {'first': 'status', 'second': 'meeting', 'third': 'customer', 'type': 'CUST'},
  {'first': 'summary', 'second': 'with', 'third': 'customer', 'type': 'CUST'},
  {'first': 'customer', 'second': 'communication', 'third': '', 'type': 'CUST'},
  {'first': 'meeting', 'second': 'with', 'third': 'customer', 'type': 'MIT'},
  {'first': 'organize', 'second': 'conference', 'third': 'call', 'type': 'CUST'},
  {'first': 'call', 'second': 'with', 'third': 'customer', 'type': 'CUST'},
  {'first': 'demo', 'second': 'meeting', 'third': 'customer', 'type': 'MIT'},
  {'first': 'brainstorm', 'second': 'session', 'third': '', 'type': 'MIT'},
  {'first': 'add', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'chang', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'creat', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'fix', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'mend', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'miss', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'modif', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'prepar', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'provid', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'updat', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'writ', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'add', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'chang', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'creat', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'fix', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'mend', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'miss', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'modif', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'prepar', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'provid', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'updat', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'writ', 'second': 'help', 'third': 'text', 'type': 'DOC'},
  {'first': 'add', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'chang', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'creat', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'fix', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'mend', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'miss', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'modif', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'prepar', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'provid', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'updat', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'writ', 'second': 'help', 'third': 'message', 'type': 'DOC'},
  {'first': 'wiki', 'second': 'page', 'third': '', 'type': 'DOC'},
  {'first': 'internal', 'second': 'help', 'third': '', 'type': 'DOC'},
  {'first': 'technical', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  {'first': 'business', 'second': 'documentation', 'third': '', 'type': 'DOC'},
  #poprawki 10.01.2024
  {'first': 'travel', 'second': 'dest', 'third': '', 'type': 'CUST'},
  {'first': 'travel', 'second': '-', 'third': '', 'type': 'CUST'},
  {'first': 'travel', 'second': '', 'third': '', 'type': 'CUST'},
  {'first': 'qa', 'second': '-', 'third': '', 'type': 'TST'},
  {'first': 'access', 'second': 'for', 'third': '', 'type': 'ADM'},
  {'first': 'access', 'second': 'to', 'third': '', 'type': 'ADM'},
  {'first': 'not', 'second': 'work', 'third': 'environment', 'type': 'ADM'},
  {'first': 'hot', 'second': 'fix', 'third': 'delivery', 'type': 'ADM'},
  {'first': 'environment', 'second': 'ram', 'third': '', 'type': 'ADM'},
  {'first': 'jira', 'second': 'plan', 'third': '', 'type': 'PM'},
  # poprawki 13.01.2024
  {'first': 'demo', 'second': 'sprint', 'third': '', 'type': 'RQM'},
  {'first': 'expose', 'second': 'ip', 'third': 'server', 'type': 'ADM'},
  

  ]

def matches_keywords(keywords, text):
    result = 0
    if keywords['first'] in text:
        result = 1
        if keywords['second']:
            if keywords['second'] in text:
                result = 2
                if keywords['third']:
                    if keywords['third'] in text:
                        result = 3
                    else:
                        result = 0
            else:
                result = 0
    return result

def classify_text(text, list=keywords_list, debug=False):
    result = {}
    text = text.lower()
    for keywords in keywords_list:
        matches_count = matches_keywords(keywords, text)
        if matches_count > 0:
            if debug:
                print(f'{keywords} == {matches_count}')
            result[keywords['type']] = result.get(keywords['type'], 0) + matches_count
    return result

def max_class(class_dict):
    max_value = 0
    max_key = ''
    for key in class_dict.keys():
        if max_value < class_dict[key]:
            max_value = class_dict[key]
            max_key = key
    return max_key
